# This file is intended for automation only. Use at your own risk.

services:
  mariadb:
    image: mariadb
    hostname: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=domjudge
      - MYSQL_USER=domjudge
      - MYSQL_PASSWORD=domjudge
      - MYSQL_DATABASE=domjudge
    ports:
      - 13306:3306
    command: --max-connections=1000 --max-allowed-packet=512M
    volumes:
      - /var/lib/mysql
  domjudge:
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:12345"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 1m
    image: domjudge/domserver
    hostname: domserver
    depends_on:
      - mariadb
    ports:
      - 12345:80
    volumes:
      - ${PWD}/affilDOMjudge:/opt/domjudge/domserver/webapp/public/images/affiliations
  #  entrypoint: ["/bin/bash","-c","sleep 1m && /scripts/start.sh"]
  #  hostname: domserver
  #  #privileged: true
